version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: ccm-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ccm_dev
      POSTGRES_USER: ccm_admin
      POSTGRES_PASSWORD: ccm_local_password
    volumes:
      - ccm_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ccm_admin -d ccm_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ccm-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ccm.local
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  ccm_pgdata:
